### ISSUE TITLE
wget可以指定网卡进行认证吗

### ISSUE THREAD

**Issue by Ozzy-hzy** [rainvalley/Srun_Linux#5]
之前用你的脚本curl加了--interface参数可以指定虚拟网卡能多账号叠加，wget不知道能不能实现。

**Comment by rainvalley** [comment]
wget --bind-address=ADDRESS

**Comment by rainvalley** [comment]
在这里可以看到wget的manual：https://www.gnu.org/software/wget/manual/wget.html

**Comment by Ozzy-hzy** [comment]
好的，晚上回去试试

**Comment by rainvalley** [comment]
没想到真有人在用（

**Comment by chillsoul** [comment]
能实现网速叠加？

**Comment by Ozzy-hzy** [comment]
> 能实现网速叠加？

可以的
